services:
  aryanattapt-mongodb:
    image: mongo:latest
    container_name: aryanattapt-mongodb
    restart: always
    ports:
      - 50000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 16M
    networks:
      - aryanattapt-network

  aryanattapt-postgresql:
    image: postgres:latest
    container_name: aryanattapt-postgresql
    restart: always
    ports:
      - 50001:5432
    volumes:
      - ~/../apps/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 100M
    networks:
      - aryanattapt-network

  aryanattapt-redis:
    image: redis:latest
    container_name: aryanattapt-redis
    restart: always
    ports:
      - 50002:6379
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 16M
    networks:
      - aryanattapt-network

  aryanattapt-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: aryanattapt-elasticsearch
    restart: always
    ports:
      - 50003:9200
      - 50004:9300
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elasticsearch
      - ELASTIC_PASSWORD=elasticsearch
      - ES_JAVA_OPTS=-Xms512m -Xmx2g
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 128M
    networks:
      - aryanattapt-network

networks:
  aryanattapt-network:
    name: aryanattapt-network
    external: true
    
#docker network create -d bridge aryanattapt-network