services:
  aryanattapt-mongodb:
    image: mongo:latest
    container_name: aryanattapt-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 400M
        reservations:
          cpus: '0.1'
          memory: 16M
    networks:
      - aryanattapt-network

  aryanattapt-postgresql:
    image: postgres:latest
    container_name: aryanattapt-postgresql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/../apps/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 100M
    networks:
      - aryanattapt-network

  aryanattapt-redis:
    image: redis:latest
    container_name: aryanattapt-redis
    restart: always
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.1'
          memory: 16M
    networks:
      - aryanattapt-network

networks:
  aryanattapt-network:
    name: aryanattapt-network
    external: true
    
#docker network create -d bridge aryanattapt-network