services:
  aryanattapt-rabbitmq:
    image: rabbitmq:management
    container_name: aryanattapt-rabbitmq
    restart: always
    ports:
      - "10000:5672"    # RabbitMQ default port for client communication
      - "10001:15672"  # RabbitMQ management web UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin    # Default username
      - RABBITMQ_DEFAULT_PASS=admin    # Default password
    volumes:
      - ~/../apps/rabbitmq:/var/lib/rabbitmq  # Persist RabbitMQ data across container restarts
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 100M
    networks:
      - aryanattapt-network

networks:
  aryanattapt-network:
    name: aryanattapt-network
    external: true
    
#docker network create -d bridge aryanattapt-network