services:
  aryanattapt-netdata:
    image: netdata/netdata:latest
    container_name: aryanattapt-netdata
    ports:
      - "50020:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 16M
    volumes:
      - ~/../apps/netdataconfig:/etc/netdata
      - ~/../apps/netdatalib:/var/lib/netdata
      - ~/../apps/netdatacache:/var/cache/netdata
      - ~/../apps/etc/passwd:/host/etc/passwd:ro
      - ~/../apps/etc/group:/host/etc/group:ro
      - ~/../apps/proc:/host/proc:ro
      - ~/../apps/sys:/host/sys:ro
      - ~/../apps/etc/os-release:/host/etc/os-release:ro
    environment:
      - TZ=Asia/Jakarta
      - NETDATA_CLAIM_TOKEN=      # Optional: for Netdata Cloud (leave blank or remove if unused)
      - NETDATA_CLAIM_URL=        # Optional: for Netdata Cloud
    restart: always
    networks:
      - aryanattapt-network

networks:
  aryanattapt-network:
    external: true