services:
  aryanattapt-n8n:
    image: n8nio/n8n
    container_name: aryanattapt-n8n
    ports:
      - "5001:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=n8n.aryanattapt.my.id
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.aryanattapt.my.id
      - VUE_APP_URL_BASE_API=https://n8n.aryanattapt.my.id/
      - TZ=Asia/Jakarta
    volumes:
      - ~/../apps/n8n_data:/home/node/.n8n
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 16M
    networks:
      - aryanattapt-network

networks:
  aryanattapt-network:
    name: aryanattapt-network
    external: true